package com.example.suburban;

import android.os.Bundle;

import androidx.fragment.app.Fragment;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.GridView;

public class Fragment_Round extends Fragment {


    GridView gridView;

    public Fragment_Round() {
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        View view = inflater.inflate(R.layout.fragment__round, container, false);
        gridView = view.findViewById(R.id.gd);
        String [] pname = {

                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas" ,
                "Addidas"
        };

String [] prices = {
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123",
        "Rs.123"

};

        int[] images = {
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck,
                R.drawable.neck


        };

        products_adapter pd = new products_adapter (getContext(),images, prices , pname);
        gridView.setAdapter(pd);

        return view;

    }
}